# Generated by Django 4.0.1 on 2022-01-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
